<script type="text/javascript">
    <?php /*
		belboonTag = {
			"gdpr": "[value]",
			"gdprConsent": "[value]",
            "productBrand": "[value]",
		    "orderProducts": [
	            {
	                "id": "[value]",
	                "price": "[value]",
	                "qty": "[value]"
	            }
	        ]
	    };
	*/ ?>
    belboonTag = <?php echo json_encode($params);?>;
</script>
