<script type="text/javascript">
    <?php /*
        belboonTag = {
			"gdpr": "[value]",
			"gdprConsent": "[value]",
	        "orderId": "[value]",
	        "orderProducts": [
	            {
	                "id": "[value]",
	                "price": "[value]",
	                "qty": "[value]"
	            }
	        ],
	        "orderTransactionAmount": "[value]"
        };
	*/ ?>
    belboonTag = <?php echo json_encode($params);?>;
</script>
