<script type="text/javascript">
    <?php /*
        belboonTag = {
			"gdpr": "[value]",
			"gdprConsent": "[value]",
		    "productBrand": "[value]",
	        "categoryId": "[value]",
	        "products": [
	            {
	                "id": "[value]",
	                "price": "[value]"
	            }
	        ]
        };
	*/?>
    belboonTag = <?php echo json_encode($params);?>;
</script>
