<!-- BEGIN BELBOON - PERFORMANCE MARKETING NETWORK TRACKING CODE version 4.25 -->
<script type="text/javascript">
var itsConv = {
	trcCat : '<?php echo $trc;?>',
	convTarget : '<?php echo $ctg;?>',
	siteId : '<?php echo $sid;?>',
	convId : '<?php echo $cid;?>',
	csi : '<?php echo $csi;?>',
	ordValue : '<?php echo $orv;?>',

	<?php if(isset($gdpr) === true):?>
		// TCFv2.0 parameters
		gdpr : '<?php echo $gdpr;?>',
		// '0' GDPR does not apply; '1' GDPR applies
	<?php endif;?>
	<?php if(isset($gdpr_consent) === true):?>
		gdprConsent : '<?php echo $gdpr_consent;?>',
		// Only meaningful if gdpr=1. URL-safe base64-encoded TC string obtained from the CMP JS API or OpenRTB.
	<?php endif;?>

	// OPTIONAL FIELDS: These are session tracking parameters
	clickId  : '<?php echo $cli;?>',
	ordCurr : '<?php echo $orc;?>',

	advId : '<?php echo $advertiser_id;?>',
	trcDomain : '<?php echo $tracking_domain;?>'
};
// DO NOT CHANGE. The following lines assure tracking functionality.
en=function(v){if(v){if(typeof(encodeURIComponent)=='function'){return(encodeURIComponent(v));}return(escape(v));}};ts=function(){var d=new Date();var t=d.getTime();return(t);};im=function(s){if(document.images){if(typeof(ia)!="object"){
var ia=new Array();};var i=ia.length;ia[i]=new Image();ia[i].src=s;ia[i].onload=function(){};}else{document.write('<img src="'+s+'" height="1" width="1" border="0" alt="" style="display:none;">');}};var pr='https:';
fr=function(s){var d=document;var i=d.createElement("iframe");i.src=s;i.frameBorder=0;i.width=0;i.height=0;i.vspace=0;i.hspace=0;i.marginWidth=0;i.marginHeight=0;i.scrolling="no";i.allowTransparency=true;i.style.display="none";try{d.body.insertBefore(i,d.body.firstChild);}catch(e){
d.write('<ifr'+'ame'+' src="'+s+'" width="0" height="0" frameborder="0" vspace="0" hspace="0" marginwidth="0" marginheight="0" scrolling="no" allowtransparency="true" style="display:none;"></ifr'+'ame>');}};ap=function(o){var v='tst='+ts();if(o.trcCat){v+='&trc='+en(o.trcCat);}
v+='&ctg='+en(o.convTarget);v+='&cid='+en(o.convId);if(o.ordValue){v+='&orv='+en(o.ordValue);}if(o.ordCurr){v+='&orc='+en(o.ordCurr);}if(o.discValue){v+='&dsv='+en(o.discValue);}if(o.discOrdValue){v+='&ovd='+en(o.discOrdValue);}if(o.discCode){v+='&dsc='+en(o.discCode);}
if(o.invValue){v+='&inv='+en(o.invValue);}if(o.confStat){v+='&cfs='+en(o.confStat);}if(o.admCode){v+='&amc='+en(o.admCode);}if(o.payMethod){v+='&pmt='+en(o.payMethod);}if(o.subCode){v+='&smc='+en(o.subCode);}if(o.userVal1){v+='&uv1='+en(o.userVal1);}if(o.userVal2){v+='&uv2='+en(o.userVal2);}if(o.userVal3){
v+='&uv3='+en(o.userVal3);}if(o.userVal4){v+='&uv4='+en(o.userVal4);}if(o.isCustNew){var n=o.isCustNew.toLowerCase();v+='&csn=';v+=(n=="true"||n=="false")?n:"null";}if(o.custId){v+='&csi='+en(o.custId);}if(o.custGend){var g=o.custGend.toLowerCase();v+='&csg=';
v+=(g=="m"||g=="f")?g:"null";}if(o.custAge){v+='&csa='+en(o.custAge);}if(o.basket){v+='&bsk='+en(o.basket);}if(o.addData){v+='&adt='+en(o.addData);}if(o.uniqid){v+='&uniqid='+en(o.uniqid);}if(o.clickIds && o.clickIds.length > 0){v+='&cli='+en(o.clickIds.join(','));}else if(o.clickId){v+='&cli='+en(o.clickId);}if(o.custSurv){v+='&csr='+en(o.custSurv);}if(o.siteId){v+='&sid='+en(o.siteId);}var s=(screen.width)?screen.width:"0";
s+="X";s+=(screen.height)?screen.height:"0";s+="X";s+=(screen.colorDepth)?screen.colorDepth:"0";v+='&scr='+s;v+='&nck=';v+=(navigator.cookieEnabled)?navigator.cookieEnabled:"null";v+='&njv=';v+=(navigator.javaEnabled())?navigator.javaEnabled():"null";if (o.locationHref){v+='&hrf='+en(o.locationHref);}if(o.gdpr){v+='&gdpr='+en(o.gdpr);}if(o.gdprConsent){v+='&gdpr_consent='+en(o.gdprConsent);}v+='&ver='+en('4.25');return(v);};
itsStartConv=function(o){var s=pr+'//'+o.trcDomain+'/ts/'+o.advId+'/tsa?typ=f&'+ap(o);fr(s);};itsStartConv(itsConv);

var a = document.createElement('script'); a.type = 'text/javascript'; a.async = true; a.src = 'https://'+itsConv.trcDomain+'/scripts/ts/'+itsConv.advId+'contA.js'; var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(a, s);

</script>
<noscript>
<!-- ------------ SET THE PARAMETERS FOR NOSCRIPT PART HERE ---------------- -->
    <!-- The parameter values have to be set in realtime. Every special characters have to be URL-encoded. -->
	<!-- gdpr: '0' GDPR does not apply; '1' GDPR applies -->
	<!-- gdpr_consent: Only meaningful if gdpr=1. URL-safe base64-encoded TC string obtained from the CMP JS API or OpenRTB. -->
	<!--               Must contain consent for Vendor ID of advertiser or for 871 as default  -->
    <img src="<?php echo $pixel_url;?>" width="1" height="1" border="0" style="display:none;">
</noscript>
<!-- END BELBOON - PERFORMANCE MARKETING NETWORK TRACKING CODE -->
